name: Three Wise Men
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#473256'
    - '#ea1d5a'
    - '#1dabea'
    - '#807389'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
